//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccSubHeadsDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccSubHeadsDT()
        {
            this.ExPDTs = new HashSet<ExPDT>();
        }
    
        public int HeadID { get; set; }
        public Nullable<int> AccID { get; set; }
        public string Accounts { get; set; }
        public string AccTypes { get; set; }
    
        public virtual AccHeadDT AccHeadDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExPDT> ExPDTs { get; set; }
    }
}
