//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assigned_test_DT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assigned_test_DT()
        {
            this.Pat_InvestList = new HashSet<Pat_InvestList>();
        }
    
        public long AssignID { get; set; }
        public Nullable<int> PatieintID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string AadharNos { get; set; }
        public Nullable<int> AgeYear { get; set; }
        public Nullable<int> Inmonth { get; set; }
        public Nullable<int> InDays { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string AddressDetails { get; set; }
        public string CollectionCenter { get; set; }
        public int DoctorID { get; set; }
        public int SampleColAgents { get; set; }
        public Nullable<decimal> TotRs { get; set; }
        public Nullable<decimal> Discounts { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string PayMode { get; set; }
        public Nullable<int> PakageID { get; set; }
        public Nullable<int> PanelID { get; set; }
        public Nullable<int> TestID { get; set; }
        public string TsetName { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string GrpName { get; set; }
        public Nullable<int> TSRNo { get; set; }
        public Nullable<int> GSRNO { get; set; }
        public string LoginID { get; set; }
        public Nullable<bool> ResultSTs { get; set; }
        public Nullable<bool> SyncSts { get; set; }
        public Nullable<int> HID { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pat_InvestList> Pat_InvestList { get; set; }
    }
}
