//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExPDT
    {
        public long ExpID { get; set; }
        public int AccountID { get; set; }
        public Nullable<System.DateTime> ExDate { get; set; }
        public string Remarks { get; set; }
        public decimal Amount { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> Edate { get; set; }
        public string ESTS { get; set; }
        public long HID { get; set; }
        public string EType { get; set; }
        public string PayMode { get; set; }
        public string ChqNo { get; set; }
        public string Chqdate { get; set; }
    
        public virtual AccSubHeadsDT AccSubHeadsDT { get; set; }
    }
}
