//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabCompany
    {
        public int Company_ID { get; set; }
        public string Company_Name { get; set; }
        public string Address { get; set; }
        public string Landmark { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Pincode { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Email_ID { get; set; }
        public string Website { get; set; }
        public string Reg_No { get; set; }
        public string Slogan1 { get; set; }
        public string Slogan2 { get; set; }
        public string Logo { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Edited_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Edited_On { get; set; }
        public string StateCode { get; set; }
        public string MsgSend { get; set; }
    }
}
