//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabITEMDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabITEMDT()
        {
            this.LabPurchaseDTs = new HashSet<LabPurchaseDT>();
        }
    
        public long ITEMID { get; set; }
        public Nullable<int> HID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> OPQTY { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string Createdby { get; set; }
        public Nullable<int> BrID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabPurchaseDT> LabPurchaseDTs { get; set; }
    }
}
