//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabPurchaseDT
    {
        public long PurchId { get; set; }
        public int HID { get; set; }
        public int VendorID { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string Units { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> GSTP { get; set; }
        public Nullable<decimal> GSTMAT { get; set; }
        public Nullable<decimal> DisPer { get; set; }
        public Nullable<decimal> Grands { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<long> ITEMID { get; set; }
    
        public virtual LabITEMDT LabITEMDT { get; set; }
        public virtual VendorDT VendorDT { get; set; }
    }
}
