//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pat_InvestList
    {
        public long LabSrNo { get; set; }
        public long RegsID { get; set; }
        public Nullable<int> PkgID { get; set; }
        public Nullable<int> PnlID { get; set; }
        public Nullable<int> TestID { get; set; }
        public string TestNames { get; set; }
        public Nullable<int> TOrderNos { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int DoctorID { get; set; }
    
        public virtual Assigned_test_DT Assigned_test_DT { get; set; }
    }
}
