//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferalDT
    {
        public int RefId { get; set; }
        public string Referal_Name { get; set; }
        public string MobileNos { get; set; }
        public string Address { get; set; }
        public decimal ComP { get; set; }
        public bool Ref_Status { get; set; }
        public string RefType { get; set; }
        public string Specialization { get; set; }
        public string Degree { get; set; }
    }
}
