//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestDT()
        {
            this.TestParameterDTs = new HashSet<TestParameterDT>();
            this.ReferenceValuesDTs = new HashSet<ReferenceValuesDT>();
        }
    
        public long Test_ID { get; set; }
        public string Test_Name { get; set; }
        public Nullable<decimal> Test_Rate { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public string Group_Name { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Edited_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Edited_On { get; set; }
        public string T_ShortName { get; set; }
        public string Method_Name { get; set; }
        public string Instruemnt { get; set; }
        public string Interpretation { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
    
        public virtual GroupDT GroupDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestParameterDT> TestParameterDTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceValuesDT> ReferenceValuesDTs { get; set; }
    }
}
