//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultDT
    {
        public long RecordSRNo { get; set; }
        public long RAssignID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<long> PatientID { get; set; }
        public Nullable<int> DrID { get; set; }
        public Nullable<int> GRPID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> ParamID { get; set; }
        public Nullable<int> TSrNo { get; set; }
        public string GroupName { get; set; }
        public string TestName { get; set; }
        public string Parm_Name { get; set; }
        public string Sub_Param { get; set; }
        public string Ref_Min { get; set; }
        public string Ref_Max { get; set; }
        public string InputResult { get; set; }
        public string InputRemarks { get; set; }
        public string TestRemarks { get; set; }
        public string LabTechnician { get; set; }
        public string TestedIn { get; set; }
        public string ReportRemarks { get; set; }
        public string TUnit { get; set; }
        public Nullable<decimal> Minref { get; set; }
        public Nullable<decimal> MAXref { get; set; }
        public Nullable<decimal> CMin_ref { get; set; }
        public Nullable<decimal> CMAX_ref { get; set; }
        public Nullable<decimal> CompValues { get; set; }
        public Nullable<int> GSRNO { get; set; }
        public Nullable<int> TeSRNO { get; set; }
        public Nullable<int> PSRNO { get; set; }
        public string Printsts { get; set; }
    }
}
