//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsPanel
    {
        public int PanelID { get; set; }
        public string PanelName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string TestNames { get; set; }
        public Nullable<decimal> Fees { get; set; }
    }
}
