//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsPackagesDT
    {
        public int PSRNO { get; set; }
        public int PackageID { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> PanelID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public string Panel_Test_Namelist { get; set; }
    }
}
