//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int RID { get; set; }
        public string LoginID { get; set; }
        public string Modules { get; set; }
        public string AddRecord { get; set; }
        public string EditRecord { get; set; }
        public string DeleteRecord { get; set; }
        public string DelPass { get; set; }
        public string EditPass { get; set; }
    }
}
