//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_DT
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string Old_Password { get; set; }
        public string New_Password { get; set; }
        public string Re_Password { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Edited_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Edited_On { get; set; }
        public string LoginID { get; set; }
        public string Modules { get; set; }
        public string DoctorsName { get; set; }
        public string MobileNo { get; set; }
    }
}
