//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorDT()
        {
            this.LabPurchaseDTs = new HashSet<LabPurchaseDT>();
        }
    
        public int VID { get; set; }
        public string VendorName { get; set; }
        public string GSTIN { get; set; }
        public string Address { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> OpBal { get; set; }
        public Nullable<int> HID { get; set; }
        public Nullable<bool> SyncSts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabPurchaseDT> LabPurchaseDTs { get; set; }
    }
}
